  
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
server:
  port: ${PORT:${SERVER_PORT:0}}
---
spring:
  profiles: subject
  application:
    name: lab-5-eureka-subject
words: I,You,He,She,It

---
spring:
  profiles: verb
  application:
    name: lab-5-eureka-verb
words: ran,knew,had,saw,bought

---
spring:
  profiles: article
  application:
    name: lab-5-eureka-article  
words: a,the

---
spring:
  profiles: adjective
  application:
    name: lab-5-eureka-adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring:
  profiles: noun
  application:
    name: lab-5-eureka-noun
words: boat,book,vote,seat,backpack,partition,groundhog

---
spring:
  profiles: cold-noun
  application:
    name: lab-5-eureka-noun #note here the application name should be same for replicas
words: icicle,refrigerator,blizzard,snowball

---
spring:
  profiles: sentence
  application:
    name: lab-5-eureka-sentence  
server:
  port: 8021
feignclient:
  subject: lab-5-eureka-subject
  noun: lab-5-eureka-noun
  adjective: lab-5-eureka-adjective
  verb: lab-5-eureka-verb
